In [0]:
## importing important packages
import numpy as np
import pandas as pd
import re

In [0]:

df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN',
'londON_StockhOlm',

'Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
'12. Air France', '"Swiss Air"']})


In [3]:
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [34]:
len(df['RecentDelays'][1])

0

In [0]:
From=[]
To=[]
from_to= ['LoNDon_paris', 'MAdrid_miLAN','londON_StockhOlm','Budapest_PaRis', 'Brussels_londOn']
for element in from_to:
   ele=element.split('_')
   From.append(ele[0].lower().title())
   To.append(ele[1].lower().title())

In [5]:
print(From)
print(To)

['London', 'Madrid', 'London', 'Budapest', 'Brussels']
['Paris', 'Milan', 'Stockholm', 'Paris', 'London']


In [6]:
'''

df['FlightNumber'][1]=df['FlightNumber'][0]+10
df['FlightNumber'][3]=df['FlightNumber'][2]+10
df['FlightNumber']
'''

"\n\ndf['FlightNumber'][1]=df['FlightNumber'][0]+10\ndf['FlightNumber'][3]=df['FlightNumber'][2]+10\ndf['FlightNumber']\n"

In [7]:
for i in df['FlightNumber']:
  print(i)

10045.0
nan
10065.0
nan
10085.0


In [8]:
nan_index=list(np.where(df['FlightNumber'].isnull())[0])
type(nan_index)

list

In [9]:
## updating the flight number as per the requirements given
for i in nan_index:
  df['FlightNumber'][i]=df['FlightNumber'][i-1]+10

df['FlightNumber']  

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


0    10045.0
1    10055.0
2    10065.0
3    10075.0
4    10085.0
Name: FlightNumber, dtype: float64

In [43]:
## Cleaning the Air lines names in standard form

Air_Line=[]
Airline=[]
for i in df['Airline']:
  
  for j in re.split (r'[!<>.1-9"()' ']',i):  
     if j!="":
       Air_Line.append(j)
for i in Air_Line:
     if i!=' ':
       Airline.append(i)
Airline        

       

['KLM', 'Air France', 'British Airways', ' Air France', 'Swiss Air']

In [37]:
## Separating and making new separate columns for delays
delay_1=[]
delay_2=[]
delay_3=[]
delay_4=[]
delay_5=[]
for i in df['RecentDelays']:
  if len(i)==0:
    
        delay_1.append(np.nan)
        delay_2.append(np.nan)
        delay_3.append(np.nan)
        delay_4.append(np.nan)
        delay_5.append(np.nan)
       
  elif len(i)==1:
    
       delay_1.append(i[0])
       delay_2.append(np.nan)
       delay_3.append(np.nan)
       

  elif len(i)==2:
    
       delay_1.append(i[0])
       delay_2.append(i[1])
       delay_3.append(np.nan)
       
  elif len(i)==3:
    
       delay_1.append(i[0])
       delay_2.append(i[1])
       delay_3.append(i[2])
           
       
print(delay_1)    
print(delay_2)    
print(delay_3)    



[23, nan, 24, 13, 67]
[47, nan, 43, nan, 32]
[nan, nan, 87, nan, nan]


In [31]:
Delay_1

array([23, 24, 13, 67])

In [13]:
Delay_2

array([47, 43, 32])

In [14]:
Delay_3

array([87])

In [17]:
##Shalow copying the original dataframe into a new one
df_new=df
df_new

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN       10055.0            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis       10075.0          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [0]:
## Droping the 'From_To' column
df_new.drop(['From_To'],axis=1,inplace=True)

In [46]:
## Making new Dataframe out of the old one
df_new['From']=From
df_new['To']=To
df_new['Flight_Number']=df['FlightNumber']
df_new['Delay_1']=delay_1
df_new['Delay_2']=delay_2
df_new['Delay_3']=delay_3
df_new['Airline']=Airline
df_new.drop(['RecentDelays','FlightNumber'],axis=1,inplace=True)
df_new


Airline      From         To  ...  Delay_1  Delay_2  Delay_3
0              KLM    London      Paris  ...     23.0     47.0      NaN
1       Air France    Madrid      Milan  ...      NaN      NaN      NaN
2  British Airways    London  Stockholm  ...     24.0     43.0     87.0
3       Air France  Budapest      Paris  ...     13.0      NaN      NaN
4        Swiss Air  Brussels     London  ...     67.0     32.0      NaN

[5 rows x 7 columns]